### ISSUE TITLE
Provision jenkins with plugins

### ISSUE THREAD

**Issue by jpic** [saltstack-formulas/jenkins-formula#23]
It would be great if jenkins-formula could install plugins. I have a poc a bit like this (edited for clarity) that could be worked out to be included in the formula:

```
{%- set cli = 'java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar' %}

jobs_dependencies:
  pkg.installed:
    - pkgs:
      - curl

jenkins_is_started:
  service.running:
    - name: jenkins

jenkins_port_bound:
  cmd.run: 
    - name: until curl -s -I http://localhost:8080 | grep X-Jenkins-CLI2-Port &> /dev/null; do sleep 1; done
    - stateful: True
    - require:
      - service: jenkins_is_started

jenkins_online:
  cmd.run:
    - name: while curl {{ jenkins.cli_url }} | grep -i restarting &> /dev/null; do sleep 1; done
    - stateful: True
    - env: 
      - JENKINS_URL: {{ jenkins.cli_url }}
    - require:
      - cmd: jenkins_port_bound

jenkins_updates_directory:
  file.directory:
    - name: /var/lib/jenkins/updates/
    - user: jenkins
    - group: jenkins
    - makedirs: True

jenkins_ready_for_plugins:
  cmd.run:
    - unless: test -f /var/lib/jenkins/updates/default.json
    - name: "wget http://updates.jenkins-ci.org/update-center.json -qO- | sed '1d;$d' > /var/lib/jenkins/updates/default.json"
    - require: 
      - cmd: jenkins_online
      - file: jenkins_updates_directory

{% for plugin in jenkins.plugins.installed %}
jenkins_plugin_{{ plugin }}:
  cmd.run:
    # we should rather call list-plugins once and then grep on the result in the loop
    - unless: {{ cli }} list-plugins | grep {{ plugin }}
    - name: {{ cli }} install-plugin {{ plugin }}
    - timeout: 360
    - env: 
      - JENKINS_URL: {{ jenkins.cli_url }}
    - require:
      - cmd: jenkins_ready_for_plugins 
{% endfor %}

jenkins_restart_for_plugins:
  service.running:
    - name: jenkins
    - watch:
      {% for plugin in jenkins.plugins.installed %}
      - cmd: jenkins_plugin_{{ plugin }}
      {% endfor %}
```

So as you can see there's a lot of boilerplate, and while this works it's far from perfect so we'd probably have to work on the PR for some weeks, but if we find this is within the scope of jenkins-formula then I could code that PR.
