### ISSUE TITLE
Plugins are not being installed

### ISSUE THREAD

**Issue by djibi2** [saltstack-formulas/jenkins-formula#43]
Salt is configured to run in stand-alone mode and has formula properly configured.  I've created a pillar based on the example but added the plugins I need.  When I run the following command it installs Jenkins but none of the plugins are installed:

`sudo salt-call state.sls jenkins saltenv=ci` 
 
My pillar/jenkins.sls file is:

```
jenkins:
  lookup:
    port: 80
    home: /var/lib/jenkins
    user: jenkins
    group: www-data
    server_name: localhost
    master_url: http://localhost:8080
    plugins:
      installed:
        - any-buildstep
        - chroot
        - copyartifact
        - cron_column
        - cvs
        - environment-dashboard
        - environment-script
        - github-oauth
        - pollscm
        - publish-over-ssh
        - slack
        - ssh-slaves
        - subversion
        - thinbackup
        - translation
        - windows-slaves
    pkgs:
      - jenkins

```
