### ISSUE TITLE
nginx States are hard coded and not friendly for Centos/Redhat

### ISSUE THREAD

**Issue by byteknacker** [saltstack-formulas/jenkins-formula#48]
Problem:

When I try to use jenkins.nginx to install nginx config for jenkins, it does not work on Centos 7 since sites-available and enabled are not the correct folders. 

Solution:

I used this custom state instead:

```
# Install nginx, run nginx only if installation is successful

nginx:
  pkg.installed: []

/etc/nginx/default.d/jenkins.conf:
  file.managed:
    - source: salt://nginx/files/jenkins.conf
    - user: nginx
    - group: nginx
    - require:
      - pkg: nginx

/etc/nginx/nginx.conf:
  file.managed:
    - source: salt://nginx/files/nginx.conf
    - user: nginx
    - group: nginx
    - require:
      - pkg: nginx

Run nginx when everything is ready:
  service.running:
    - name: nginx
    - enable: True
    - reload: True
    - require:
      - pkg: nginx
    - watch:
      - file: /etc/nginx/default.d/jenkins.conf
      - file: /etc/nginx/nginx.conf
```

The files are placed at the usual directories within the nginx directory I created. 

Proposed Solution:

To get rid of the hard coded version and make further centos and redhat friendly version available through map.jinja and pillar. Make the source file pillar configurable and the map.jinja include variables for the final path of clients depending on the linux distribution.
