### ISSUE TITLE
Include flexibility to install either LTS or Dev Jenkins Version

### ISSUE THREAD

**Issue by byteknacker** [saltstack-formulas/jenkins-formula#49]
Problem:

When using jenkins to install Jenkins I always get the development version but not the stable LTS. I wish to choose which one to install.

Solution:

I used the following to extend your formula:

```
extend:
  jenkins:
    {% if grains['os_family'] in ['RedHat', 'Debian'] %}
    pkgrepo.managed:
      - humanname: Jenkins upstream package repository
      {% if grains['os_family'] == 'RedHat' %}
      # Upgrade to Jenkins 2.7 LTS
      - baseurl: http://pkg.jenkins-ci.org/redhat-stable
      - gpgkey: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
      {% elif grains['os_family'] == 'Debian' %}
      - file: {{jenkins.deb_apt_source}}
      - name: deb http://pkg.jenkins-ci.org/debian binary/
      - key_url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
      {% endif %}
      - require_in:
        - pkg: jenkins
    {% endif %}
    pkg.installed:
      - pkgs: {{ jenkins.pkgs|json }}
    service.running:
      - enable: True
      - watch:
        - pkg: jenkins
```

Proposed Solution:

I wish to propose that you add a variable for the repo distro, i think it is just an one liner. Include this in the map.jinja and pillar so users can use pillar to choose whether to install LTS or the dev version of Jenkins. 

If I have the time, I will definitely make a PR. Let me know if you have the time to do it yourself soon, otherwise, I can try to make some time on my side asap. Just wish to know your time schedule so I don't work on the same thing as you do.
